name: Sync Local Branches

on:
  schedule:
    # Schedule for Sync Upstream: Every Saturday at 5:00 UTC
    - cron: '0 5 * * 6'
    # Schedule for Update Stable Branch: Every Saturday at 6:00 UTC
    - cron: '0 6 * * 6'
  
  workflow_dispatch:
    inputs:
      action:
        description: 'Select the action to run'
        required: true
        type: choice
        options:
          - Sync Upstream
          - Update Stable Branch
          - Run All

jobs:
  # This job handles the Upstream Sync, whether from a schedule or manual trigger
  upstream_sync_job:
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 5 * * 6') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Sync Upstream') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Run All')
    uses: mamolinux/github-actions/.github/workflows/sync-with-upstream.yml@main
    with:
      upstream: 'linuxmint/xed'
      target_branch: 'master'

  # This job handles the Stable Branch Update, whether from a schedule or manual trigger
  stable_update_job:
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 6 * * 6') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Update Stable Branch') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Run All')
    uses: mamolinux/github-actions/.github/workflows/update-stable-branch.yml@main
    with:
      target_branch: 'mamolinux/stable'
